Update compile.yml

diff --git a/.github/workflows/compile.yml b/.github/workflows/compile.yml
--- a/.github/workflows/compile.yml
+++ b/.github/workflows/compile.yml
@@ -27,20 +27,20 @@ jobs:
           sudo -E apt-get clean > /dev/null 2>&1
           
           echo -e "\033[34m🔧 Configuring environment \033[0m"
-          PKG_NAME_PHP7=luci-app-radmon-php7
-          PKG_PHP7_VER=$(grep 'PKG_VERSION:=' $PKG_NAME_PHP7/Makefile | awk -F '=' '{print $2}' | tr -d ' ')
-          PKG_NAME_PHP8=luci-app-radmon-php8
-          PKG_PHP8_VER=$(grep 'PKG_VERSION:=' $PKG_NAME_PHP8/Makefile | awk -F '=' '{print $2}' | tr -d ' ')
+          PKG_PHP7_NAME=luci-app-radmon-php7
+          PKG_PHP7_VER=$(grep 'PKG_VERSION:=' $PKG_PHP7_NAME/Makefile | awk -F '=' '{print $2}' | tr -d ' ')
+          PKG_PHP8_NAME=luci-app-radmon-php8
+          PKG_PHP8_VER=$(grep 'PKG_VERSION:=' $PKG_PHP8_NAME/Makefile | awk -F '=' '{print $2}' | tr -d ' ')
           export TERM=xterm
           
           echo "PKG_PHP7_VER=$PKG_PHP7_VER" >> $GITHUB_ENV
-          echo "PKG_NAME_PHP7=$PKG_NAME_PHP7" >> $GITHUB_ENV
-          echo -e "\033[34m\t📦 PKG_NAME_PHP7:\033[37m $PKG_NAME_PHP7 \033[0m"
+          echo "PKG_PHP7_NAME=$PKG_PHP7_NAME" >> $GITHUB_ENV
+          echo -e "\033[34m\t📦 PKG_PHP7_NAME:\033[37m $PKG_PHP7_NAME \033[0m"
           echo -e "\033[34m\t🔖 PKG_PHP7_VER:\033[37m $PKG_PHP7_VER \033[0m"
           
           echo "PKG_PHP8_VER=$PKG_PHP8_VER" >> $GITHUB_ENV
-          echo "PKG_NAME_PHP8=$PKG_NAME_PHP8" >> $GITHUB_ENV
-          echo -e "\033[34m\t📦 PKG_NAME_PHP8:\033[37m $PKG_NAME_PHP8 \033[0m"
+          echo "PKG_PHP8_NAME=$PKG_PHP8_NAME" >> $GITHUB_ENV
+          echo -e "\033[34m\t📦 PKG_PHP8_NAME:\033[37m $PKG_PHP8_NAME \033[0m"
           echo -e "\033[34m\t🔖 PKG_PHP8_VER:\033[37m $PKG_PHP8_VER \033[0m"
           
           echo -e "\033[34m\t💻 TERM:\033[37m xterm \033[0m"
@@ -53,8 +53,8 @@ jobs:
 
           echo -e "\033[34m📦 Cloning packages \033[0m"
           git clone -q https://github.com/${{ github.repository }} sdk/package/tmp
-          mv sdk/package/tmp/${PKG_NAME_PHP7} sdk/package/
-          mv sdk/package/tmp/${PKG_NAME_PHP8} sdk/package/
+          mv sdk/package/tmp/${PKG_PHP7_NAME} sdk/package/
+          mv sdk/package/tmp/${PKG_PHP8_NAME} sdk/package/
           rm -rf sdk/package/tmp
             
       - name: 📡 Set up SDK feeds
@@ -74,17 +74,23 @@ jobs:
           sed -i '/^CONFIG_LUCI_JSMIN=/d' .config
           sed -i '/^CONFIG_LUCI_CSSTIDY=/d' .config
 
-          echo -e "\033[34m🔨 Compiling ${PKG_NAME_PHP7} package \033[0m"
-          make package/${PKG_NAME_PHP7}/{clean,compile} -j$(nproc) > /dev/null 2>&1
+          echo -e "\033[34m🔨 Compiling ${PKG_PHP7_NAME} package \033[0m"
+          make package/${PKG_PHP7_NAME}/{clean,compile} -j$(nproc) > /dev/null 2>&1
 
           echo -e "\033[34m📦 Compilation completed: \033[0m"
           PKG_PHP7_PATH=$(find bin/packages/x86_64/luci/ -name 'luci-app-radmon-php7*.ipk')
-          PKG_PHP7_FILE=$(basename $PKG_PHP7_PATH)
-          echo "PKG_PHP7_PATH=sdk/$PKG_PHP7_PATH" >> $GITHUB_ENV
-          echo "PKG_PHP7_FILE=$PKG_PHP7_FILE" >> $GITHUB_ENV
-          echo -e "\033[34m\t📂 Package path:\033[37m $PKG_PHP7_PATH \033[0m"
-          echo -e "\033[34m\t📄 Package file:\033[37m $PKG_PHP7_FILE \033[0m"
           
+          if [ -n "$PKG_PHP7_PATH" ]; then
+              PKG_PHP7_FILE=$(basename $PKG_PHP7_PATH)
+              echo "PKG_PHP7_PATH=sdk/$PKG_PHP7_PATH" >> $GITHUB_ENV
+              echo "PKG_PHP7_FILE=$PKG_PHP7_FILE" >> $GITHUB_ENV
+              echo -e "\033[34m\t📂 Package path:\033[37m $PKG_PHP7_PATH \033[0m"
+              echo -e "\033[34m\t📄 Package file:\033[37m $PKG_PHP7_FILE \033[0m"
+          else
+              echo "Error: Package file not found."
+              exit 1
+          fi
+
       - name: ⚙️ Configure & compile luci-app-radmon-php8
         run: |
           echo -e "\033[34m🔧 Configuring SDK \033[0m"
@@ -93,17 +99,23 @@ jobs:
           sed -i '/^CONFIG_LUCI_JSMIN=/d' .config
           sed -i '/^CONFIG_LUCI_CSSTIDY=/d' .config
 
-          echo -e "\033[34m🔨 Compiling ${PKG_NAME_PHP8} package \033[0m"
-          make package/${PKG_NAME_PHP8}/{clean,compile} -j$(nproc) > /dev/null 2>&1
+          echo -e "\033[34m🔨 Compiling ${PKG_PHP8_NAME} package \033[0m"
+          make package/${PKG_PHP8_NAME}/{clean,compile} -j$(nproc) > /dev/null 2>&1
 
           echo -e "\033[34m📦 Compilation completed: \033[0m"
           PKG_PHP8_PATH=$(find bin/packages/x86_64/luci/ -name 'luci-app-radmon-php8*.ipk')
-          PKG_PHP8_FILE=$(basename $PKG_PHP8_PATH)
-          echo "PKG_PHP8_PATH=sdk/$PKG_PHP8_PATH" >> $GITHUB_ENV
-          echo "PKG_PHP8_FILE=$PKG_PHP8_FILE" >> $GITHUB_ENV
-          echo -e "\033[34m\t📂 Package path:\033[37m $PKG_PHP8_PATH \033[0m"
-          echo -e "\033[34m\t📄 Package file:\033[37m $PKG_PHP8_FILE \033[0m"
-
+          
+          if [ -n "$PKG_PHP8_PATH" ]; then
+              PKG_PHP8_FILE=$(basename $PKG_PHP8_PATH)
+              echo "PKG_PHP8_PATH=sdk/$PKG_PHP8_PATH" >> $GITHUB_ENV
+              echo "PKG_PHP8_FILE=$PKG_PHP8_FILE" >> $GITHUB_ENV
+              echo -e "\033[34m\t📂 Package path:\033[37m $PKG_PHP8_PATH \033[0m"
+              echo -e "\033[34m\t📄 Package file:\033[37m $PKG_PHP8_FILE \033[0m"
+          else
+              echo "Error: Package file not found."
+              exit 1
+          fi
+          
       - name: 🚀 Generate new tag & release
         uses: softprops/action-gh-release@v2
         env:
@@ -120,8 +132,8 @@ jobs:
             ### Changelog for release v${{ env.PKG_PHP7_VER }}
 
             **New builds of luci-app-radmon packages:**
-            - ${{ env.PKG_NAME_PHP7 }}
-            - ${{ env.PKG_NAME_PHP8 }}
+            - ${{ env.PKG_PHP7_NAME }}
+            - ${{ env.PKG_PHP8_NAME }}
 
       - name: 📬 Send notification to Telegram
         run: |
