Update radmon_php7.yml

diff --git a/.github/workflows/radmon_php7.yml b/.github/workflows/radmon_php7.yml
--- a/.github/workflows/radmon_php7.yml
+++ b/.github/workflows/radmon_php7.yml
@@ -10,7 +10,7 @@ on:
 
 jobs:
   build:
-    name: Compile Radmon PHP7
+    name: Compile Radmon PHP8
     runs-on: ubuntu-latest
 
     steps:
@@ -21,13 +21,13 @@ jobs:
         run: |
           echo -e "\033[34m Preparing build environment \033[0m"
           sudo -E apt-get update > /dev/null 2>&1
-          sudo -E apt-get install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget > /dev/null 2>&1
+          sudo -E apt-get install subversion build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget > /dev/null 2>&1
           sudo -E apt-get autoremove --purge > /dev/null 2>&1
           sudo -E apt-get clean > /dev/null 2>&1
           
           echo -e "\033[34m Configuring environment \033[0m"
           PKG_NAME=luci-app-radmon-php7
-          PKG_VERSION=PKG_VERSION=$(grep 'PKG_VERSION:=' ./luci-app-radmon-php7/Makefile | awk -F '=' '{print $2}')
+          PKG_VERSION=$(grep 'PKG_VERSION:=' ./luci-app-radmon-php7/Makefile | awk -F '=' '{print $2}')
           export TERM=xterm
           echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
           echo "PKG_NAME=$PKG_NAME" >> $GITHUB_ENV
@@ -39,11 +39,10 @@ jobs:
         run: |
           echo -e "\033[34m Downloading SDK OpenWRT \033[0m"
           curl -s -L https://downloads.openwrt.org/releases/23.05.5/targets/x86/64/openwrt-sdk-23.05.5-x86-64_gcc-12.3.0_musl.Linux-x86_64.tar.xz -o sdk.tar.xz
-          mkdir sdk && tar -xf sdk.tar.xz -C sdk --strip-components=1
+          mkdir -p sdk && tar -xf sdk.tar.xz -C sdk --strip-components=1
 
           echo -e "\033[34m Cloning $PKG_NAME package \033[0m"
-          rm -rf sdk/package
-          git clone -q https://github.com/Maizil41/luci-app-radius-monitor sdk/package/
+          cd sdk/package && git init && git remote add origin https://github.com/Maizil41/luci-app-radius-monitor.git && git config core.sparseCheckout true && echo "luci-app-radmon-php7/*" >> .git/info/sparse-checkout && git pull origin main
 
       - name: Set up SDK feeds
         run: |
@@ -57,17 +56,23 @@ jobs:
       - name: Configure & compile IPK
         run: |
           echo -e "\033[34m Configuring SDK \033[0m"
-          cd sdk && make defconfig > /dev/null 2>&1
+          cd sdk && make defconfig
           rm -rf feeds/luci/contrib/package/csstidy
           sed -i '/^CONFIG_LUCI_JSMIN=/d' .config
           sed -i '/^CONFIG_LUCI_CSSTIDY=/d' .config
 
           echo -e "\033[34m Compiling ${PKG_NAME} package \033[0m"
-          make package/${PKG_NAME}/{clean,compile} -j$(nproc) > /dev/null 2>&1
+          make clean > /dev/null 2>&1
+          make package/${PKG_NAME}/compile -j1 > /dev/null 2>&1
 
           echo -e "\033[34m Compilation completed: \033[0m"
-          PKG_PATH=$(find bin/packages/x86_64/luci/ -name 'luci-app-*.ipk')
-          PKG_FILE=$(basename $PKG_PATH)
+          PKG_PATH=$(find bin/packages/x86_64/luci/ -name "${PKG_NAME}.ipk")
+          if [ -z "$PKG_PATH" ]; then
+            echo -e "\033[31m Error: Package not found! \033[0m"
+            exit 1
+          fi
+          
+          PKG_FILE=$(basename "$PKG_PATH")
           echo "PKG_PATH=sdk/$PKG_PATH" >> $GITHUB_ENV
           echo "PKG_FILE=$PKG_FILE" >> $GITHUB_ENV
           echo -e "\033[34m\t Package path:\033[37m $PKG_PATH \033[0m"
@@ -95,4 +100,3 @@ jobs:
                -F document=@"${{ env.PKG_PATH }}" \
                -F caption="New package ${{ env.PKG_FILE }} (version ${{ env.PKG_VERSION }}) has been compiled and is ready for use." \
                https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendDocument
-
